### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#1]
- [x] Add PWA futures to the APP

https://vite-pwa-org.netlify.app/guide/ 

**User Story**: As a user of SmartSpend, I want to be able to install the app on my device as a Progressive Web App (PWA), so that I can access it quickly and easily without needing to open a web browser.

**Acceptance Criteria**:

- The app should be designed as a PWA, with a service worker and a manifest file that enables installation.
- When I visit the app in a supported browser (e.g. Chrome, Firefox), I should see a prompt asking me if I want to install the app as a PWA.

**Comment by nikita-remeslov** [comment]
@jhoneysoup This task not about your **User Story**
Here we should have the functional to install PWA on our device.

Example:  https://app.starbucks.com/

![Image](https://user-images.githubusercontent.com/78347072/225310553-2b9f4f0e-827e-4e77-929c-07000e8ce9ba.png)

**Comment by jhoneysoup** [comment]
tested

![Image](https://user-images.githubusercontent.com/122827384/225589079-7c0a5a9e-cd65-400c-a12d-75b2a38ddd24.png)



![Image](https://user-images.githubusercontent.com/122827384/225589248-43795935-4b0c-4b12-baf5-6dd03cf0af2f.png)



![Image](https://user-images.githubusercontent.com/122827384/225589916-2628ade9-fed1-4ac5-b7e4-7d178cee3efd.png)
