### ISSUE TITLE
Add AUTH hook for check permission

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#103]
- [x] Add hook to check JWT token on private routes
- [x] Update existing routes

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/230022926-bb3d47c4-8b0f-45ad-938e-4f1f3b09d069.png)



![Image](https://user-images.githubusercontent.com/122827384/230023046-114a75d4-0871-4783-b497-f6cd2be27a79.png)



![Image](https://user-images.githubusercontent.com/122827384/230023670-ce30014c-41da-46d5-9ec6-7ad4365d8f2a.png)



![Image](https://user-images.githubusercontent.com/122827384/230023758-f6c84513-2696-4f68-bd83-aa884bd87733.png)
