### ISSUE TITLE
Add UI to show, create, update, delete transactions

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#127]
![Image](https://user-images.githubusercontent.com/78347072/227155574-5ada2b9e-2e7e-4a4d-bc1b-37b5e82fdc8c.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231135812-523c433b-e980-4d6b-a12d-8f68315454dc.png)
