### ISSUE TITLE
Add API to create, update, delete transactions

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#128]
**User Story:**

As an authorized user, I want to create, update and delete transactions, so that I can control and manage my finances.

**Acceptance Criteria:**

The API for creating/updating transactions should accept the following input parameters:
- category
- date
- note
- label
- amount
- currency (only for creating)

API for deleting transactions should delete any transaction by ID.

**Comment by daria-kostiuk** [comment]
Tested:

- [ ] create transaction:

![Image](https://user-images.githubusercontent.com/114158510/230886300-5a24db43-a828-4985-8584-c665734b78af.png)

- [ ] all transaction:

![Image](https://user-images.githubusercontent.com/114158510/230886385-519d7f56-3f2c-41c6-a82b-c7ffbd2b8bf4.png)

- [ ] edit transaction:

![Image](https://user-images.githubusercontent.com/114158510/230887143-10e61571-026f-4ba1-9fc6-b5b02b0a234d.png)


- [ ] delete transaction:

![Image](https://user-images.githubusercontent.com/114158510/230887278-7be7365b-b8a8-4c5d-b0c7-88f9dad7ab5e.png)
![Image](https://user-images.githubusercontent.com/114158510/230887325-b59a58eb-98e4-4d56-b5b7-bbf379b3a6da.png)
