### ISSUE TITLE
Add API to create, update, delete budgets

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#129]
**User Story:**

As an authorized user, I want to create, update and delete budgets, so that I can control and manage my finances.

**Acceptance Criteria:**

The API for creating/updating budgets should accept the following input parameters:

- budget name
- amount
- currency
- budget filter: wallets, categories
- budget period: recurrence, start date

API for deleting budgets should delete any budget by ID.

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/230052263-4ca3583d-c157-40e4-b9a4-d0b763d8298f.png)

![Image](https://user-images.githubusercontent.com/114158510/230052983-c27eab76-922a-4b41-b0b9-a8e41359c9fb.png)

![Image](https://user-images.githubusercontent.com/114158510/230053107-a2d00ae5-5dae-4fc2-95ba-061fa5f5333f.png)

![Image](https://user-images.githubusercontent.com/114158510/230053223-bc5f8e76-c148-4299-89d6-ceb4e46cf4b3.png)

![Image](https://user-images.githubusercontent.com/114158510/230053653-a85b165f-eac0-4044-bade-549190c0fffb.png)

![Image](https://user-images.githubusercontent.com/114158510/230053717-4f35da95-047f-4047-8f00-11be8a899a5a.png)
