### ISSUE TITLE
Public and Private routing

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#13]
- [x] Public route
- [x] Private route

**User Story**: As a user of the SmartSpend, I want to be able to access public pages without logging in and private pages after logging in, so that I can manage my financial information securely.

**Acceptance Criteria**:

- User should be able to access the home page, about page, and contact page without logging in.
- If user try to access a private page (e.g. dashboard, account settings) without logging in, user should be redirected to the login page.
- If user try to access the login or sign-up pages while already logged in, user should be redirected to the dashboard page.

**Comment by jhoneysoup** [comment]
Tested:
After deleting the token and reloading the page, access to the dashboard (private page) is closed.


![Image](https://user-images.githubusercontent.com/122827384/227951411-fbd558d8-545b-4fbf-bbeb-995346b25548.png)



![Image](https://user-images.githubusercontent.com/122827384/227951491-b87d09f2-c948-414e-bb19-90afc65a1ea8.png)
