### ISSUE TITLE
[BUG] Wrong link format on Sign Up page

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#147]
**Description:**
Wrong link format on Sign Up page

**Environment:**
OS: Windows 11
Browser: Google Chrome
Version: 111.0.5563.110

**Steps to reproduce:**

1. Open https://smartspend.netlify.app/sign-up

**Actual Result:**
All phrase "No account? Sign Up" is link

**Expected Result:**
Only "Sign Up" part should be a link

**Visual Proof (screenshots, videos, text):**
![image](https://user-images.githubusercontent.com/122827384/227339692-6d617a96-a577-4a91-93eb-3345b6d0c63b.png)

**Severity:**
Minor (S4)

**Comment by teslmik** [comment]
Bug fixed in issue 135 [](https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-smartspend/pull/143)

**Comment by VItaliy-Kalenichenko** [comment]
Try to avoid such decisions in the future. One ticket one pull request
