### ISSUE TITLE
Add Transaction table

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#151]
![Image](https://user-images.githubusercontent.com/78347072/227491072-5a4ba0fe-871d-4116-91f0-67c748856092.png)

![Image](https://user-images.githubusercontent.com/78347072/227491403-5e678d12-327b-4d8a-a21c-0d4d9b7598f7.png)

**Comment by jhoneysoup** [comment]
Tested:

- [ ] component added

- [ ] checkboxes working

![Image](https://user-images.githubusercontent.com/122827384/229739559-29530903-f9f2-42a2-87fd-d992b650adc6.png)
