### ISSUE TITLE
[BUG] Wrong website layout on different screens

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#152]
**Description:**
Issues with website layout on wide monitors and mobile devices

**Environment:**
OS: Windows 11
Browser: Google Chrome
Version: 111.0.5563.110 

**Steps to reproduce:**

1. Open https://smartspend.netlify.app/
2. Open dev tools and switch to responsive dimension.

**Actual Result:**
Wrong layout on wide monitors and mobile devices

**Expected Result:**
Website layout should work on different devices or screens.

**Visual Proof (screenshots, videos, text):**
![image](https://user-images.githubusercontent.com/122827384/227496652-dda0ffff-c127-4232-b341-f16c5c82a07e.png)
![image](https://user-images.githubusercontent.com/122827384/227496662-d37794f6-4757-4e99-b6c7-9ccb2a1f2c09.png)

**Severity:**

Critical (S2)

**Comment by jhoneysoup** [comment]
The container should be of this size:
![Image](https://user-images.githubusercontent.com/122827384/227497868-952ae1b5-c159-4861-a828-fdac03fda8f7.png)


We need to set a fixed size for all containers to make everything look good. Just like here:
![Image](https://user-images.githubusercontent.com/122827384/227498116-24004a77-6794-4d4a-8d31-5b5c347b0762.png)

**Comment by teslmik** [comment]
![Image](https://user-images.githubusercontent.com/16450566/227742867-7b3a7802-2448-4d7d-bb58-38cb44140850.png)



![Image](https://user-images.githubusercontent.com/16450566/227742872-9d035fba-5784-4c14-b114-ebedd4a65c71.png)



![Image](https://user-images.githubusercontent.com/16450566/227742874-a1083182-f272-463b-957c-660049ad8693.png)



![Image](https://user-images.githubusercontent.com/16450566/227742875-ac03d3e0-aae0-431c-ab3c-ef0acaff6f67.png)



![Image](https://user-images.githubusercontent.com/16450566/227742877-ab91abe4-a199-4d6a-a93a-c5c2b0dac52a.png)



![Image](https://user-images.githubusercontent.com/16450566/227742879-b79ae288-cbc2-4881-8436-02c43b6b62cc.png)
