### ISSUE TITLE
Increase the size of eye icons and dots in password fields on the Log In/Sign Up pages

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#154]
Increase the size of eye icons and dots in password fields on the Log In/Sign Up. 

_Pay attention that unmasked password font shouldn’t be bigger, than email. 
Only dots need to be increased._

Sign Up:

- [x] Password field
- [x] Confirm password field

Log In:

- [x] Password field

Actual result:

![Image](https://user-images.githubusercontent.com/114158510/227535189-bf24dc1c-4f39-4b1b-a0fc-0f555376becf.png)

**Comment by teslmik** [comment]
![Image](https://user-images.githubusercontent.com/16450566/227609525-ca2103b3-2f34-4a7d-b138-e59fa7d70923.gif)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/228455249-603d2d02-0b63-495c-b703-8cc24b8ef153.png)

![Image](https://user-images.githubusercontent.com/114158510/228455567-9cdee729-7814-4d99-a981-aacfaddff68b.png)
