### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#166]

**Comment by Evcat6** [comment]
![Image](https://user-images.githubusercontent.com/93705949/227902320-376305b0-dfe2-46c4-a962-92cbc4596b8b.png)

**Comment by jhoneysoup** [comment]
Tested: 

- [ ] as authorized user "Go to Home" button redirects to dashboard
- [ ] as unauthorized user "Go to Home" button redirects to Login/Registration page



![Image](https://user-images.githubusercontent.com/122827384/227944233-a27fe75f-8690-4ca8-8470-3e08f7ba9832.png)
