### ISSUE TITLE
Add budget details page

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#167]
**User Story**: As a user of SmartSpend, I want to be able to view detailed information about my budget, so that I can better understand my spending habits and make informed decisions about my finances.

**Acceptance criteria**:

- Page available for authorized users.
- User should be able to edit budget by budget name, amount, currency, budget category filter, budget period.
- User should be able to delete budget
- User should be able to see/hide all periods.
- User should be able to see "Accounted categories" and "Accounted wallets" charts 
- User should be able to edit/delete budgets transactions and attach photo to them.

![Image](https://user-images.githubusercontent.com/122827384/227962145-8a9eff06-2e6d-424d-bd45-ab84ceeefe3f.png)

![Image](https://user-images.githubusercontent.com/122827384/227964857-37ee8689-30e2-468c-b56b-7521b560ecc6.png)

![Image](https://user-images.githubusercontent.com/122827384/227962225-03ae794c-75ce-4aa0-a605-8ec50e309d96.png)

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/230353806-c8f51a60-4634-46ba-b929-370244b2831f.png)



![Image](https://user-images.githubusercontent.com/122827384/230354100-c03fce86-baba-430e-a7c0-376f0e070f47.png)
