### ISSUE TITLE
Add widget wrappers for charts

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#169]
![Image](https://user-images.githubusercontent.com/78347072/227867854-f5fefe21-a741-4cdb-a049-5fb57fc4b391.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231367636-6c2a8169-03c7-4615-b337-c6d2963e3304.png)
