### ISSUE TITLE
Add modal for adding wallets

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#170]
![Image](https://user-images.githubusercontent.com/78347072/227868052-e20a6934-cbd0-4e4c-93f0-300e64a1c976.png)

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/229543684-be5b5f3a-1393-4386-bf19-c9dd5c447dbd.png)
