### ISSUE TITLE
Add common Loader component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#171]
Create a few examples for a vote. Use styles of our website

![Image](https://user-images.githubusercontent.com/78347072/227923163-2af5d141-0912-4347-9175-a5321b21fac3.png)

**Comment by jhoneysoup** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/122827384/228763296-dc406a90-e1ce-42d8-91db-7c7fbe57cc18.gif)
