### ISSUE TITLE
Add logo element according to design

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#174]
When the user clicks on the logo, they should be redirected to the root page (landing page).

https://www.figma.com/file/OCDRyX8GemPhtyk3seZBRU/SmartSpend?node-id=1595-481&t=qlaUnftRscXlFawF-0

![Image](https://user-images.githubusercontent.com/122827384/227906250-4a15768f-47f2-469b-9a4a-acf2f178e709.png)

![Image](https://user-images.githubusercontent.com/122827384/227906046-5eca7888-3e18-4445-9e1a-e8c2bd397396.png)

![Image](https://user-images.githubusercontent.com/122827384/227906090-8ef18f9b-7d51-43be-a267-dfff87d9e083.png)

![Image](https://user-images.githubusercontent.com/122827384/227906180-276bb175-adbe-4d16-92f9-c0bc639f8eab.png)

**Comment by nikita-remeslov** [comment]
I don't see any linked PR

**Comment by teslmik** [comment]
Sorry

**Comment by jhoneysoup** [comment]
Tested:

- [ ] Logo added

![Image](https://user-images.githubusercontent.com/122827384/228811126-5ae3a88d-6699-4a93-ba34-4b5feb509eb7.png)



![Image](https://user-images.githubusercontent.com/122827384/228811175-a8c62a08-aa8d-4130-a67f-933f572749e0.png)



![Image](https://user-images.githubusercontent.com/122827384/228811229-5d0e8b00-78f6-4e69-8e52-d66f0a8b946c.png)



![Image](https://user-images.githubusercontent.com/122827384/228811256-2d8995df-1e60-482b-80d1-f0c73811c157.png)

- [ ] Logo redirects to Landing page
