### ISSUE TITLE
Update UI page

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#177]
Add collapse items for each component
https://www.npmjs.com/package/react-collapse

Example: swagger doc item

- [x] Create UI bundle
- [x] Update UI page
- [x] Create components for each common component with mock
- [x] Add code highlight - https://www.npmjs.com/package/prism-react-renderer
- [x] Add some styles, to show these components to the client

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/229039445-56736523-11c3-4a38-ba03-05c5e2adbcc0.png)
