### ISSUE TITLE
Connect wallets in dashboard to backend

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#213]
![Image](https://user-images.githubusercontent.com/105710998/228756384-d915dd40-45fc-451b-8b3c-b8ea39a80ef7.png)

**Comment by jhoneysoup** [comment]
Tested:

- [ ] wallet create

![Image](https://user-images.githubusercontent.com/122827384/230623901-6b917766-2f4c-441f-9e2a-cd8db9e28050.png)

![Image](https://user-images.githubusercontent.com/122827384/230624123-3834f605-1cca-4a5f-949f-4c7481891e68.png)

- [ ] wallet delete


![Image](https://user-images.githubusercontent.com/122827384/230624173-0c50dc72-358d-4ed9-b116-8174e630d5e4.png)

- [ ] wallet edit


![Image](https://user-images.githubusercontent.com/122827384/230624444-da4523f9-a50c-469f-b63a-640b4c1a0e68.png)
