### ISSUE TITLE
[BUG] Server crashes when it is starting

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#214]

**Comment by jhoneysoup** [comment]
tested:


![Image](https://user-images.githubusercontent.com/122827384/228804318-809e8f75-7260-4278-845a-0755f8c2657a.png)



![Image](https://user-images.githubusercontent.com/122827384/228804508-4c25899d-2aec-4aa3-acf9-576836f2a0b4.png)
