### ISSUE TITLE
[BUG] Horizontal and vertical scrolls on auth pages

### ISSUE THREAD

**Issue by Evcat6** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#232]
![Image](https://user-images.githubusercontent.com/93705949/228892561-ee93bdf4-7c44-4f14-9704-d82fee3e39ec.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/229033398-ce19932a-bf81-4441-9f3d-c6dfdf2e6574.png)
