### ISSUE TITLE
Dropdown refactoring

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#238]
- [x] separate folders for each type of dropdown
- [x] Props types duplications. You have this type in a separate file. 

![Image](https://user-images.githubusercontent.com/78347072/228959478-2c2c717a-1480-435d-9164-1968f3a9dda5.png)

- [x] Import from root file

![Image](https://user-images.githubusercontent.com/78347072/228959712-ca787568-87e5-4e8c-8e46-7a1bb9e9aae6.png)

- [x] useCallback from common hooks
- [x] scss variables better import to styles. I don't see how you use it

![Image](https://user-images.githubusercontent.com/78347072/228961260-10db8536-131a-4b6c-a5a4-fc9c6e846d90.png)

All comments related to both dropdowns.

**Comment by nikita-remeslov** [comment]
@MstyslavDmytryk label, milestone

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/229492682-e0cc863f-52b7-4ecf-a02c-261de9c5e2e5.png)

![Image](https://user-images.githubusercontent.com/114158510/229492712-774c6f30-2c9e-4423-8c41-d692006e3195.png)

![Image](https://user-images.githubusercontent.com/114158510/229492750-02c4c7fe-e5e3-4347-bddd-b8a5cea55ee1.png)
