### ISSUE TITLE
Add footer menu when size of the screen is small

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#241]
![Image](https://user-images.githubusercontent.com/105710998/229101922-9204e101-287a-4101-8181-35c6f19f7f15.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/230309765-5d0e60aa-e503-4017-bdd9-e46aee5590c4.png)

![Image](https://user-images.githubusercontent.com/114158510/230309859-337d3ddc-4c66-47d7-bcd0-e7edfdd4988a.png)
