### ISSUE TITLE
[BUG] header on 404 page

### ISSUE THREAD

**Issue by Evcat6** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#243]
![Image](https://user-images.githubusercontent.com/93705949/229071574-85cc47a9-ddf0-4e75-9685-f4fd062450a5.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/229478440-86dc9639-0fb3-465f-8636-b30548592ef8.png)
