### ISSUE TITLE
Change name of  App in document head

### ISSUE THREAD

**Issue by Evcat6** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#245]
Change page titles:

- [x] Landing: _SmartSpend_
- [x] Sign up: _Sign Up | SmartSpend_
- [x] Log in: _Log In | SmartSpend_
- [ ] Account settings: _Account | SmartSpend_
- [x] Dashboard: _Dashboard | SmartSpend_
- [ ] Transactions: _Transactions | SmartSpend_
- [ ] Overview: _Overview | SmartSpend_
- [ ] Budgets: _Budgets | SmartSpend_

![Image](https://user-images.githubusercontent.com/114158510/229449140-61652c08-6424-469f-a531-e15f612cf14a.png)

**Comment by Evcat6** [comment]
Some routes does not exists yet

**Comment by daria-kostiuk** [comment]
@Evcat6

Remove the vertical line from the title on the Landing page:
- [ ] must be **SmartSpend**, not **| SmartSpend**

![Image](https://user-images.githubusercontent.com/114158510/230011835-81a87bf0-6b88-43da-9e1e-3caefd1fbf8b.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/230327062-b3c34dcb-717f-41d7-b721-0ac5c32e7288.png)

![Image](https://user-images.githubusercontent.com/114158510/230327157-30453504-c18a-4679-9af1-69e1e79522dd.png)

![Image](https://user-images.githubusercontent.com/114158510/230327214-292ed078-af20-4572-adb9-a57d45550387.png)

![Image](https://user-images.githubusercontent.com/114158510/230335149-01bb3a59-2246-4cfb-acfd-a11af4accd3a.png)
