### ISSUE TITLE
Add seeds to fill the currency database

### ISSUE THREAD

**Issue by teslmik** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#252]
Add seeds to fill the currency database
Currency table must contain id, name, currency symbol($, ₴, etc.)

**Comment by VItaliy-Kalenichenko** [comment]
@teslmik Add link to pr

**Comment by jhoneysoup** [comment]
Tested:

currencies
![Image](https://user-images.githubusercontent.com/122827384/229492827-bbe073b0-36fd-4ffb-bb63-6ff0d70d46a5.png)


categories
![Image](https://user-images.githubusercontent.com/122827384/229492932-f73dd37d-7837-4aef-b0ef-ab2c77dce46c.png)
