### ISSUE TITLE
[BUG] Invalid migrations queue

### ISSUE THREAD

**Issue by Evcat6** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#253]
![Image](https://user-images.githubusercontent.com/93705949/229340928-a8887e6a-a125-4eed-8f34-c11206fb9179.png)

Invalid queue of migrations what gives us this error

![Image](https://user-images.githubusercontent.com/93705949/229340958-8abbab82-726b-4513-843d-7b432b499c41.png)

what is the problem, when we start the migration in the database, the first thing we get is this error because migration user_profile  is started faster than migration add_autogenerate_uuid_extension

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/229513629-962c20ab-8aaf-472f-9d90-53f8c9bbfbd2.png)
