### ISSUE TITLE
Connect budgets to backend

### ISSUE THREAD

**Issue by teslmik** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#258]

**Comment by daria-kostiuk** [comment]
Tested:

- [ ] create
![Image](https://user-images.githubusercontent.com/114158510/230837590-1413cd0d-749a-4f84-b57c-72d6041512b9.png)

- [ ] edit
![Image](https://user-images.githubusercontent.com/114158510/230837742-2d4a3ba6-4d05-4463-8f06-8d881fc71b96.png)

- [ ] delete
