### ISSUE TITLE
Add email sending service

### ISSUE THREAD

**Issue by Evcat6** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#262]
Add email sending service who will send email to the user email after sign up
## email sending services:
https://nodemailer.com/about/

## Template:
https://www.figma.com/file/OCDRyX8GemPhtyk3seZBRU/SmartSpend?node-id=1854-1102&t=Aiq7oqy4maazqpsF-0

**Comment by Evcat6** [comment]
How To get All credentials to this api:

1. Create new Google Account

![Image](https://user-images.githubusercontent.com/93705949/229911388-2f6c53dc-b01a-42a6-92d9-a9aa697b8084.png)

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/230378034-8c6a3d35-f81a-455a-af3e-81f1f065c926.png)
