### ISSUE TITLE
Replace categoryId's with full categories in budget API

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#273]
replace categoriesId with categories here and in other responses

![Image](https://user-images.githubusercontent.com/105710998/228557318-bda8979c-1be8-44af-b6a5-d5e4854631e7.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/230052263-4ca3583d-c157-40e4-b9a4-d0b763d8298f.png)

![Image](https://user-images.githubusercontent.com/114158510/230052983-c27eab76-922a-4b41-b0b9-a8e41359c9fb.png)

![Image](https://user-images.githubusercontent.com/114158510/230053107-a2d00ae5-5dae-4fc2-95ba-061fa5f5333f.png)

![Image](https://user-images.githubusercontent.com/114158510/230053223-bc5f8e76-c148-4299-89d6-ceb4e46cf4b3.png)

![Image](https://user-images.githubusercontent.com/114158510/230053653-a85b165f-eac0-4044-bade-549190c0fffb.png)

![Image](https://user-images.githubusercontent.com/114158510/230053717-4f35da95-047f-4047-8f00-11be8a899a5a.png)
