### ISSUE TITLE
[BUG] invalid response in authorization plugin

### ISSUE THREAD

**Issue by Evcat6** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#277]
Example:

![Image](https://user-images.githubusercontent.com/93705949/229541460-24576184-0f6d-403e-9523-b307f044e954.png)

**Comment by jhoneysoup** [comment]
Tested: 


![Image](https://user-images.githubusercontent.com/122827384/230015489-6d2a3077-d125-4e1f-b55d-5713222d20df.png)


![Image](https://user-images.githubusercontent.com/122827384/230022335-97801a4f-d739-49d2-975f-fc0c71d63564.png)



undefined route:

![Image](https://user-images.githubusercontent.com/122827384/230016292-563a635a-af3d-410d-8d01-78076bacef78.png)
