### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#28]
- [x] Migration
- [x] Model
- [x] Controler
- [x] Validation

**User Story**: As a new user, I want to sign up for the SmartSpend app so that I can access my financial information and manage my funds.

**Acceptance Criteria**:

- The sign-up component should have fields for the email address, password and oauth2 (Google/Facebook buttons to sign via social networks).
- The email address should be validated to ensure that it is a valid email address and that it has not already been registered with the app.
- After registration, the unique email and encrypted password should be recorded in the database.
- In case of registration through oauth2, the first and last name will also be added to the database if they were permitted.

**Comment by jhoneysoup** [comment]
Tested

with valid creds: 


![Image](https://user-images.githubusercontent.com/122827384/226850407-b8d53eb8-63ac-456a-87b5-f45a7caa38f2.png)

with invalid email (without @):


![Image](https://user-images.githubusercontent.com/122827384/226851535-96a1bf0c-ffa1-4746-bc58-05e6851f8a22.png)

with invalid email (without dot):


![Image](https://user-images.githubusercontent.com/122827384/226851737-3b795ace-c40a-43ba-8758-ae5a6cae808b.png)

with invalid email (dot at the begining of local part):


![Image](https://user-images.githubusercontent.com/122827384/226855335-d770410f-fea2-4143-a329-89aa6bcf9b73.png)

with invalid email (dot at the end of domain part):


![Image](https://user-images.githubusercontent.com/122827384/226855601-5b24cb0a-8f96-4357-a038-8ecc099cd016.png)



with invalid password (less than required input):


![Image](https://user-images.githubusercontent.com/122827384/226852006-769ac4ba-fd3a-446f-bdff-74078218fe8c.png)

with invalid password (more than required input):


![Image](https://user-images.githubusercontent.com/122827384/226852385-a112f48d-f1cc-46ec-8eac-a19453959eec.png)

different password and repeat password:


![Image](https://user-images.githubusercontent.com/122827384/226852752-d8ec9ac5-a8d0-4536-a462-fccfb7100a5d.png)

with empty fields: 


![Image](https://user-images.githubusercontent.com/122827384/226852938-ad312641-5921-43bf-b44a-5bf434784364.png)
