### ISSUE TITLE
Add logout Button

### ISSUE THREAD

**Issue by Evcat6** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#284]
Create something like this one:

![Image](https://user-images.githubusercontent.com/93705949/229602042-e4f54d22-536a-4b2b-a428-05f51178baed.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/230567449-883dcb11-395d-4989-b76c-4703dcfdcdd2.png)
