### ISSUE TITLE
Add images storing service

### ISSUE THREAD

**Issue by Evcat6** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#285]
Suggested API: 
https://gyazo.com/
Examples of reslving this problem:

- https://github.com/BinaryStudioAcademy/thread-js/blob/production/server/src/services/image/image.service.js
- https://github.com/BinaryStudioAcademy/thread-js/blob/production/server/src/middlewares/image/image.middleware.js

**Comment by daria-kostiuk** [comment]
Closed
