### ISSUE TITLE
Replace email on first and last name on header

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#319]
- [ ] replace email on _first and last name_ on header on all private pages

![Image](https://user-images.githubusercontent.com/114158510/230305262-66009932-0b88-4269-84d8-c01ce778196c.png)

**Comment by Evcat6** [comment]
In case if we don't have this data yet we need to display email?

**Comment by daria-kostiuk** [comment]
The user must enter these data immediately after registration. So there is no need to display email.

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/230834550-4c5a3488-67e4-4c72-912b-29b1490748e2.png)

![Image](https://user-images.githubusercontent.com/114158510/230834630-1fa825da-652d-4593-ad97-7626cf96599e.png)
