### ISSUE TITLE
[BUG] Main title on the Budgets page doesn't match the design

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#336]
**Description:**
Main title on the Budgets page doesn't match the design

**Preconditions:**
1. Log in

**Environment:**
Browser - Google Chrome (111.0.5563.65)

**Steps to reproduce:**

1. Open http://localhost:3000/budgets
2. Pay attention to the main title "Budgets"

**Actual Result:**
Main title on the Budgets page doesn't match the design.
![image](https://user-images.githubusercontent.com/114158510/230403112-764497b9-d9c0-4e80-b8f3-5c4be9d46a29.png)

**Expected Result:**
Main title on the Budgets page matches the design. 
It should look the same as it does on the Dashboard page (http://localhost:3000/dashboard)
![image](https://user-images.githubusercontent.com/114158510/230403307-4ad2c112-5682-4159-970a-f93118269c57.png)

**Visual Proof (screenshots, videos, text):**
![image](https://user-images.githubusercontent.com/114158510/230401425-b0b7b037-97a4-4749-9eb0-cb1612eb572e.png)

**Severity:**
Minor (S4)

**Comment by nikita-remeslov** [comment]
Fill the ticket

![Image](https://user-images.githubusercontent.com/78347072/230571138-6bb97f07-1ba3-4c14-a44f-81243b0bb1e3.png)

**Comment by MstyslavDmytryk** [comment]
done

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/230613743-8d4701a4-abbb-4681-8b29-e55a80ea9324.png)
