### ISSUE TITLE
Connect delete account button on user settings page to backend

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#347]

**Comment by jhoneysoup** [comment]
Tested:



![Image](https://user-images.githubusercontent.com/122827384/230776535-bd144f0e-598c-4807-81fe-ef38c80942dd.png)

after clicking on "Delete account" button:


![Image](https://user-images.githubusercontent.com/122827384/230776574-f507380d-0c46-4bd0-a0f1-b01a7fd4f658.png)
