### ISSUE TITLE
Connect Budget details page elements to backend

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#366]
Connect Budget details page elements (cards, charts) to backend

**Comment by ValeriiArt** [comment]
+Accounted Categories

**Comment by jhoneysoup** [comment]
Tested: 
- [x] "You can spend" card doesn't working
- [x] fix reccurance on "Budget progress" bar.  Must show the start date and the calculated end date
- [x] remove calendar component
