### ISSUE TITLE
Add Dashboard page scaffold

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#41]
![Image](https://user-images.githubusercontent.com/78347072/225368109-deca7e0d-3f03-4be3-b763-fe97113742ce.png)

**User story**: As an authorized user, I want to be able to view and manage my financial information in a single, consolidated dashboard, so that I can easily track my spending, savings, and other key metrics.

**Acceptance criteria**:

Authorized user shall be able to see on the Dashboard page:
- tab menu
- wallets created by user
- filters
- metrics (cards with statistics)
- list of future transactions
- transactions

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/228855809-67fb0550-7ffa-4723-8489-629b92ab9af1.png)
