### ISSUE TITLE
Add wallet id to request payload when create a new transaction

### ISSUE THREAD

**Issue by Holovashcenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#427]
Depends on: 
[Connect transaction modal to backend#327](https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-smartspend/issues/327)
[Connect wallet with transactions#415](https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-smartspend/issues/415)

**Comment by teslmik** [comment]
Merge after:
https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-smartspend/issues/327
https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-smartspend/issues/415

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231138116-e90a49fb-d88b-43de-8fe3-d1d191b2c84c.png)
