### ISSUE TITLE
Add Cards

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#43]
![Image](https://user-images.githubusercontent.com/80532461/224552293-7cff7cac-af5a-4cb0-866b-ef8ee7cb6880.png)

**User Story:**

As a user, I want to see a cards with total balance/income/expenses, so that I can track the main financial metrics.

**Acceptance Criteria:**

User shall be able only to see the cards.

**Accessibility:**

Template cards are available to users on public landing page.
Cards with metrics are available to authorized users on private pages.

**Comment by daria-kostiuk** [comment]
Tested

![Image](https://user-images.githubusercontent.com/114158510/226272811-0d2d335f-83ba-4cfb-ae45-60a71d5f00f9.png)
