### ISSUE TITLE
[BUG] Responsive layout on Categories settings page doesn't behave as expected

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#431]
**Description:**
Responsive layout on Categories settings page doesn't behave as expected

**Environment:**
OS: Windows 11
Browser: Google Chrome
Version: 112.0.5615.50

**Steps to reproduce:**

1. Open https://smartspend.netlify.app/
2. Log In
3. Open https://smartspend.netlify.app/categories
4. Open dev tools
5. Change screen width to less than 465

**Actual Result:**
Responsive layout on Categories settings page doesn't working

**Expected Result:**
Responsive layout on Categories settings page works correctly on different screens.

**Visual Proof (screenshots, videos, text):**
![image](https://user-images.githubusercontent.com/122827384/230905079-f8d7ad73-93c4-4d8f-9078-d6f0be704e97.png)
![image](https://user-images.githubusercontent.com/122827384/230905105-9148e376-42ae-4f85-85ad-e55df3c05ec3.png)
![image](https://user-images.githubusercontent.com/122827384/230905142-6e2d7ddd-0528-417b-a2b5-a737b6a08f13.png)

**Severity:**
Major (S3)

**Comment by ValeriiArt** [comment]
![Image](https://user-images.githubusercontent.com/87828092/231919241-74566f0e-9fa8-45c3-a47b-24070eb6c90b.png)

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/231961971-1bb6ff48-7f63-4755-8b36-7150c0be1a12.png)
