### ISSUE TITLE
Connect Wallet details page elements with backend

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#474]
Connect Wallet details page elements (filters, cards) with backend

![Image](https://user-images.githubusercontent.com/122827384/231139634-d6dec3b7-f604-4404-9fa0-e0b1933989e0.png)

**Comment by teslmik** [comment]
Fix

**Comment by jhoneysoup** [comment]
Tested: 

- [ ] filters
- [ ] cards
