### ISSUE TITLE
Remove the mock data from the Budget card

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#495]
After creating a new budget, 500$ is deducted immediately

**Severity:**
Major (S3)

1. Open https://smartspend.netlify.app/budgets.
2. Click the "Create new Budget".
3. Create new budget (for example enter 1000$ on the Amount field).
4. Pay attention that immediately deducted 500$.

![Image](https://user-images.githubusercontent.com/114158510/231517209-2fb5bc2d-edb6-489d-90a4-c35e0432e549.png)

**Comment by ValeriiArt** [comment]
![Image](https://user-images.githubusercontent.com/87828092/231578288-5c69b25c-73a8-4e3a-8589-9b5e08a93b8e.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231669295-4b604b92-ba1d-4b67-936c-5b2a109d9790.png)
