### ISSUE TITLE
Create button components

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#5]
- [ ] Add buttons

There must be a separate BaseButton component that will be used as the base for styled buttons.

![Image](https://user-images.githubusercontent.com/80532461/224551809-723346c7-21b0-4064-93c1-2262e8c68baf.png)

**User Story**: As a user of SmartSpend, I want all the styled buttons throughout the app to be consistent and easy to use, so that I can complete my tasks efficiently and effectively.

**Acceptance Criteria:**

- All the styled buttons in the app should have a consistent style that is easy to recognize and use.
- The buttons should be easy to click on and should respond quickly to user input.
- The buttons should work well on different screen sizes and devices.

**Comment by jhoneysoup** [comment]
tested 

![Image](https://user-images.githubusercontent.com/122827384/226554342-b602d427-fbbf-4523-b9f6-58f26372ce43.png)
