### ISSUE TITLE
Update Wallet Settings page

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#513]
Bugs from @daria-kostiuk 

**It must looks like this:**

![Image](https://user-images.githubusercontent.com/114158510/231396676-198ae5d1-d4b9-4c4f-9cc4-be045c2bf365.png)

Now it looks like this:

![Image](https://user-images.githubusercontent.com/114158510/231397021-e5080f5e-143b-49b0-be7d-5bac3109b984.png)

Bugs from @jhoneysoup 

- [x] Make the tab longer and move it to the left edge (like on the user settings page)
![image](https://user-images.githubusercontent.com/122827384/230850797-32ceaabb-0832-46b3-8aa0-b9c0d59bd1f5.png)
_expected:_
![image](https://user-images.githubusercontent.com/122827384/230850842-f506f5ab-922c-441f-afb8-3afd3d978816.png)

- [x] reduce the indents on the sides and top (like on the user settings page)

![Image](https://user-images.githubusercontent.com/122827384/230854508-674b9d97-0b1d-43a7-98c1-01624f6e4dea.png)

**Comment by Evcat6** [comment]
Link pull request please

**Comment by daria-kostiuk** [comment]
@Gandrejko 
Please reduce the length of the buttons and swap them.
Also swap the buttons on the Account Settings page


Expected:
![Image](https://user-images.githubusercontent.com/114158510/231697958-3f66e67f-f4a1-4090-8a61-ff6f264c96c1.png)
![Image](https://user-images.githubusercontent.com/114158510/231698781-429aabee-376f-4ff7-8d7a-c6adfe3a5573.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231829133-f2f86301-5142-4018-99b8-928f96b020b2.png)

![Image](https://user-images.githubusercontent.com/114158510/231829178-8bde73b8-8255-4765-92d1-793d941dd7d7.png)
