### ISSUE TITLE
Add color cards to budget details page

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#515]
![Image](https://user-images.githubusercontent.com/122827384/231400347-6209e06f-076c-4005-9132-7a9ebe823ce6.png)

_should look like this:_

![Image](https://user-images.githubusercontent.com/122827384/231400447-dda7d2a4-f4fa-4b79-b3a6-aae5831ceead.png)

**Comment by Evcat6** [comment]
Link pull request please
