### ISSUE TITLE
Add percentage to Budget progress bar

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#516]
![Image](https://user-images.githubusercontent.com/122827384/231401013-a94b6e8c-7f02-4158-96d2-888c9df8d940.png)

_should look like this:_

![Image](https://user-images.githubusercontent.com/122827384/231401210-91bc7f34-6e6f-4adc-a0e3-ed9b2ac2cde7.png)

font - Rubik

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231737019-0b3dd8cc-d3ff-4388-8233-ecbde209eba2.png)
