### ISSUE TITLE
"My wallet" card on Dashboard must show current amount of money

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#519]
![Image](https://user-images.githubusercontent.com/122827384/231402460-0b52ec79-0a99-4422-9eb1-1bdf7e8061a6.png)

This card should show your wallet balance in real time, taking into account added income and expense transactions.

**Comment from @daria-kostiuk** 

"Create new Wallet" modal
- [ ] update "Balance" field: remove the placeholder and set the default to zero or let the wallet be created if this field is not filled

![Image](https://user-images.githubusercontent.com/114158510/231475362-c4a2dbe2-8b27-43a8-a07c-532dfb421619.png)

**Comment by daria-kostiuk** [comment]
Tested:

"Create new Wallet" modal:
- [ ] update "Balance" field: remove the placeholder and set the default to zero or let the wallet be created if this field is not filled
