### ISSUE TITLE
Add loader components on pages

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#533]
There should be a loader everywhere where the data is loaded, so that the page does not jump, etc. 
While the user is waiting for a server response was a loader, and then already showed the page at once with all the data

- [x] dashboard
- [x] budgets
- [x] budget details page
- [x] wallets details page

**Comment by Evcat6** [comment]
Link pull request please

**Comment by jhoneysoup** [comment]
Tested:

- [ ] dashboard


![Image](https://user-images.githubusercontent.com/122827384/231723364-c60ba989-0f03-438e-88bc-1ff85d58429a.png)

- [ ] budgets


![Image](https://user-images.githubusercontent.com/122827384/231724673-47069ad0-992a-4de3-b1f8-3820e6d91583.png)

- [ ] wallet details page


![Image](https://user-images.githubusercontent.com/122827384/231724925-550779b2-b9b3-4094-914b-521a52ca72cb.png)
