### ISSUE TITLE
Add note on the transactions table

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#542]
**Severity:**
Major (S3)

Add _note_ on the transactions table in the:

- [ ] wallet transactions page
- [ ] budget details page
- [ ] future transactions page

![Image](https://user-images.githubusercontent.com/114158510/231842125-98db8d83-80e2-4cb5-bcad-e4ff29c0eee6.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231951037-73bff525-75e2-4d78-86bf-33fd52d68d52.png)

![Image](https://user-images.githubusercontent.com/114158510/231951103-183d29d7-850a-4a77-ad20-fdde3890c2ea.png)

![Image](https://user-images.githubusercontent.com/114158510/231951132-87b6597d-51d0-4a04-8d6f-10775988d7fa.png)
