### ISSUE TITLE
[BUG] The categories icons are displayed without colour in the "Create new Budget" modal

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#544]
**Description:**
The categories _icons are displayed without colour_ on the "Budgeted for" dropdown in the "Create new Budget" modal.

**Preconditions:**
1. Log in

**Environment:**
Browser - Google Chrome (112.0.5615.50)

**Steps to reproduce:**

1. Open https://smartspend.netlify.app/budgets.
2. Click on the "Create a new Budget" button.
3. Click on the "Budgeted for" dropdown.
4. Pay attention to the icons.

**Actual Result:**
The categories _icons are displayed without colour_ on the "Budgeted for" dropdown in the "Create new Budget" modal.

**Expected Result:**
The categories _icons are displayed with colour_ on the "Budgeted for" dropdown in the "Create new Budget" modal

**Visual Proof (screenshots, videos, text):**
![image](https://user-images.githubusercontent.com/114158510/231505846-0a05b2be-82b6-4c4e-aa31-2f6069b05d4f.png)

**Severity:**
Major (S3)

**Comment by ValeriiArt** [comment]
![Image](https://user-images.githubusercontent.com/87828092/231707308-2d0edccc-0abf-4790-897c-352849f4c135.png)
