### ISSUE TITLE
[BUG] Several visual defects on the Categories Settings page

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#545]
**Description:**
Several visual defects on the Categories Settings page

**Preconditions:**
1. Log in

**Environment:**
Browser - Google Chrome (112.0.5615.50)

**Steps to reproduce:**
1. Open https://smartspend.netlify.app/user/categories.

**Bugs:**

- [x] change _Manage categories_ to _Manage Categories_ (with the uppercase letter)
![image](https://user-images.githubusercontent.com/114158510/231510655-ff9d067a-d01c-412f-9e02-94783112c311.png)

- [x] change _Delete category_ to _Delete categories_ (in the plural) and take the number in brackets
![Image](https://user-images.githubusercontent.com/114158510/231689747-b3fef798-ab00-4219-8af4-ccac6ed90bdd.png)

- [x] change _Expense category_ to _Expense Categories_ (with the uppercase letter and in the plural)
![image](https://user-images.githubusercontent.com/114158510/231511808-a3058439-1dda-4058-b892-b8384fe29b68.png)

**Actual Result:**
View of the Categories Settings page doesn't match the design

**Expected Result:**
View of the Categories Settings page matches the design

**Severity:**
Trivial (S5)

**Comment by ValeriiArt** [comment]
![Image](https://user-images.githubusercontent.com/87828092/231726202-6d772412-182b-476c-a1a2-6ce53ae86388.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231751711-12560526-e395-4683-91ca-a92d269a687b.png)
