### ISSUE TITLE
fix icons in dropdown in dashboard and wallet details page

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#554]
![Image](https://user-images.githubusercontent.com/105710998/231543113-9ebf405a-d2fb-45ae-b626-b77ae502343e.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231738121-a225e31d-c19a-475e-af84-c81b5ca0980d.png)
