### ISSUE TITLE
Add sign up page

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#56]
This page should look like the sign in page, but it should also include a password confirmation field.

**User Story**: As a new user, I want to sign up for SmartSend so that I can access my financial information and manage my funds.

**Acceptance Criteria**:

- The sign-up page should have fields for the user's email address, password, confirmation of password and oauth2 (Google/Facebook buttons to sign via social networks).
- The password field should have a minimum length of 3 characters, max length - 30.
- The email address should be validated to ensure that it is a valid email address and that it has not already been registered with the app.
- The confirmation password field should match the password field.
- If the user submits the form with invalid or missing information, appropriate error messages should be displayed indicating what information is missing or invalid.
- If the user submits the form with valid information, the user should be redirected to the dashboard.
- If the user tries to sign up with an email address that has already been registered, an error message should be displayed indicating that the email address is already in use.
- if the user enters a password, it is displayed in encrypted form, on the right side of the password field there should be a button to view the password.
- after clicking on Google (oauth2), you will be redirected to a page for choosing a Google account with which to continue registration.
- after clicking on Facebook (oauth2), you will be redirected to the Facebook page to confirm registration.

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/227276633-4dd0fc93-f65d-49f7-b7f0-04ce89814a61.png)
