### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#57]
![Image](https://user-images.githubusercontent.com/78347072/225587023-9649678f-9fff-42be-ab9b-c6c676c11278.png)

**User Story**: As a potential user of the financial web app, I want to be able to easily learn about the app's features and benefits

**Acceptance Criteria**:

- The landing page should contain link to Sign In page and top panel with tabs (Pricing, Bank Connect, Help, About Us, Blog and Contact)
- If the user is already logged in and clicked the Sign in button, user should be redirected to the Dashboard page.

**Comment by Evcat6** [comment]
# Result of markup 


![Image](https://user-images.githubusercontent.com/93705949/226205063-022e96b3-acf5-4e56-af08-351f180ed4cc.png)
