### ISSUE TITLE
Delete multiple transactions functionality

### ISSUE THREAD

**Issue by anton-otroshchenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#580]

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231800826-c065d635-3276-4194-8e1d-697da9e77407.png)
![Image](https://user-images.githubusercontent.com/114158510/231801184-20107fdf-014b-4127-893d-7c9c0d3e5675.png)
![Image](https://user-images.githubusercontent.com/114158510/231801449-7eb3ce74-0ffa-45ef-848a-f4aab1a24c12.png)
