### ISSUE TITLE
Add wallet settings icon to footer

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#596]
![Image](https://user-images.githubusercontent.com/122827384/231825748-2b717755-a68a-4c3e-8a84-80778cccb18f.png)

**Comment by MstyslavDmytryk** [comment]
Already done

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231950427-6f771d3b-bed0-4081-a15d-c5c92ec998b3.png)
