### ISSUE TITLE
Remove tab from Wallet Settings page

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#599]
- [ ] remove tab
- [ ] align the block in the center

![Image](https://user-images.githubusercontent.com/114158510/231832871-63e0a270-f2b4-418b-8aba-5520fe20fd76.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231857465-16d6e3b0-5f7c-4b21-9a70-56000b7d6ed8.png)
