### ISSUE TITLE
Create input components

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#6]
- [x] Add input component

![Image](https://user-images.githubusercontent.com/80532461/224551903-09a7d9ad-b2ef-4a80-9b69-ae6402468bcd.png)

![Image](https://user-images.githubusercontent.com/80532461/224551876-9a29ffcc-65ce-4ae4-803b-0dedf82c7c58.png)

**User Story:**

As a user, I want to be able to enter data using the input component, so that I can accurately and quickly fill out a field or form.

**Acceptance Criteria:**

User shall be able to see the various input components according to the design.

**Accessibility:**

Input components are available on public and private pages.

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/226894415-4ffdb942-d378-4073-a554-c5abfe2fe6d1.png)
