### ISSUE TITLE
[BUG] Fix "By amount" filter on the Dashboard page

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#606]
**Severity:**
Minor (S4)

If the user has no transactions yet, the slider on the Dashboard page should look like this:

![Image](https://user-images.githubusercontent.com/114158510/231844309-d783e302-78a5-4345-97cf-313452247168.png)
![Image](https://user-images.githubusercontent.com/114158510/231844072-2b34b3cb-090b-4883-96f7-6002d1938e4b.png)

**Comment by ValeriiArt** [comment]
![Image](https://user-images.githubusercontent.com/87828092/231951883-e808c451-a9a3-4630-b9ce-ff19440b20bb.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/231975586-32300489-d3fb-4b18-a942-6a38bd703c18.png)
