### ISSUE TITLE
Update Account Setting page

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#618]
**Severity:**
Minor (S4)

Change the view of the Account settings page to _which the user is redirected after registration_:

- [x] remove tabs
![Image](https://user-images.githubusercontent.com/114158510/231945134-d70753a9-75f3-4768-93cf-1266e537aab4.png)

**Comment by Evcat6** [comment]
@nikita-remeslov i think we should use mock avatar in application

**Comment by nikita-remeslov** [comment]
Yes it is better just add avatar link to DB

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/232024097-e363e99d-fdb7-471a-b31c-44512d82892a.png)
