### ISSUE TITLE
Account settings small screen z-index fix

### ISSUE THREAD

**Issue by MstyslavDmytryk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#626]
fix this

![Image](https://user-images.githubusercontent.com/102343264/231897289-5d2a9f5b-69a3-4544-98ba-cc7fe6b14b26.gif)

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/231976168-780c9f95-2951-46cc-9f5b-6fab475ce894.gif)
