### ISSUE TITLE
[BUG] Fix styles in category dropdown and future transactions items

### ISSUE THREAD

**Issue by vasylpopovych** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#652]
![Image](https://user-images.githubusercontent.com/83419134/232001181-e8cb0d2c-2263-40bb-8ae9-f3f7af9a9bec.png)

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/232024775-916a866d-c880-44b3-937f-259740385a11.png)
![Image](https://user-images.githubusercontent.com/114158510/232024815-a1f7a45e-d107-4b5f-98f3-985a58f36fca.png)
