### ISSUE TITLE
Fix the indents on the charts

### ISSUE THREAD

**Issue by jhoneysoup** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#657]
**Severity:**
Minor (S4)

_Dashboard:_
![Image](https://user-images.githubusercontent.com/122827384/232002122-a0d1fadb-d222-49e7-80c0-4211b5e3a958.png)

_Budget details page:_

![Image](https://user-images.githubusercontent.com/122827384/232002342-7216d51c-619f-442a-9cae-64746ba7ea0c.png)

**Comment by daria-kostiuk** [comment]
![Image](https://user-images.githubusercontent.com/114158510/232207784-1b08bb8c-1f31-4306-95c6-c455841a73b2.png)
