### ISSUE TITLE
[BUG] Rename 3rd card on the Budget Details page

### ISSUE THREAD

**Issue by daria-kostiuk** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#658]
**Severity:**
Major (S3)

- [x] if + or 0"Money left" (if there is still money left)
- [x] if - "Money oversent" (if the budget is overspent)
![Image](https://user-images.githubusercontent.com/114158510/232001784-c465433b-11a9-43d0-8a23-2fff44818517.png)

**Comment by nikita-remeslov** [comment]
PR link

**Comment by MstyslavDmytryk** [comment]
PR added

**Comment by daria-kostiuk** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/114158510/232070436-bdaa9a19-a3fc-4036-86ef-0117d02aa320.png)

![Image](https://user-images.githubusercontent.com/114158510/232070511-3d4a39e9-ee09-43d0-989c-ef5678ee7640.png)
