### ISSUE TITLE
Add API to create, update and delete wallets

### ISSUE THREAD

**Issue by VItaliy-Kalenichenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#66]
**User Story**: As a user of SmartSpend, I want to be able to create, update and delete wallets programmatically via the API, so that I can manage my finances programmatically and integrate the app with other financial tools.

**Acceptance Criteria**:

The API for creating wallets should accept input parameters such as wallet name, currency, and initial balance, allowing user to create new wallets with this attributes.

**Comment by jhoneysoup** [comment]
Tested:

- [ ] GET Wallets list


![Image](https://user-images.githubusercontent.com/122827384/228211330-0d1a3c1b-9062-4037-ab8f-d66de29baee2.png)


![Image](https://user-images.githubusercontent.com/122827384/228211394-e81dafcd-325a-4ecf-82e6-638228a25348.png)

- [ ] POST Wallet

![Image](https://user-images.githubusercontent.com/122827384/228211461-871c5128-9f72-4c30-a1ec-855bbd29a3ba.png)



![Image](https://user-images.githubusercontent.com/122827384/228217757-b65b305f-dd60-4db5-90d0-ecf3a6633236.png)

- [ ] GET Wallet by ID


![Image](https://user-images.githubusercontent.com/122827384/228218145-d69855e4-a94f-4ffa-8208-e664d3b2fa84.png)



![Image](https://user-images.githubusercontent.com/122827384/228218184-7687b066-8903-4ec7-9651-703738e48630.png)

- [ ] PUT Wallet


![Image](https://user-images.githubusercontent.com/122827384/228218409-5311ea4b-280b-414a-829a-1b692239f01c.png)


![Image](https://user-images.githubusercontent.com/122827384/228220956-b3cda0fc-9f95-4fc6-9be9-4e5a949c950b.png)

- [ ] DELETE Wallet


![Image](https://user-images.githubusercontent.com/122827384/228221413-7332c513-7ddd-4283-84d5-9d1694068c29.png)



![Image](https://user-images.githubusercontent.com/122827384/228221456-06d3cd60-abda-4c25-b5f7-9289f23daa87.png)
