### ISSUE TITLE
Add base modal component

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#7]
Should include: 

- [x] 1. Header
- [x] 2. Body
- [x] 3. Footer

P.S. We should use our colors

![Image](https://user-images.githubusercontent.com/78347072/224574399-30eb4fc3-84d6-47e3-82b4-6f98d4e0ea28.png)

**User Story:**

As an authorized user, I want to be able to open a modal component, so that I conveniently edit or view additional information without going to another page.

**Acceptance Criteria:**

Authorized user shall be able to close the modal component clicking on the cross/"Esc" key/"Cancel" button/blur.

**Comment by daria-kostiuk** [comment]
Tested:

close by clicking on the:
cross ✓
"Esc" key ✓
"Cancel" button ✓
"Save changes" button ✓
blur ✓

![Image](https://user-images.githubusercontent.com/114158510/226837839-a2cc5a82-b487-4aaa-ae8c-3adc0a9f8e7c.png)
