### ISSUE TITLE
Add user profile page

### ISSUE THREAD

**Issue by VItaliy-Kalenichenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#70]
![Image](https://user-images.githubusercontent.com/80532461/225850901-7da2d981-3097-4c85-8355-ed6fa8cddbfa.png)

**User Story**: As a user of the financial web app, I want to be able to view and update my account settings, so that I can customize my experience and manage my personal information.

**Acceptance criteria**:

- User should be able to upload and delete avatar.
- User should be able to update personal info such as first/last name, sex, date of birth, email.
- User should be able to change localization settings (language, currency).

**Comment by jhoneysoup** [comment]
Tested:

![Image](https://user-images.githubusercontent.com/122827384/230069033-fa4d8b35-2c46-4ce7-ab51-55f30417c8af.png)
