### ISSUE TITLE
Add categories settings page

### ISSUE THREAD

**Issue by VItaliy-Kalenichenko** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#71]
![Image](https://user-images.githubusercontent.com/80532461/225851150-8794f36e-72c5-4a8f-aa4c-214f144b67ab.png)

**User Story**: As a user of the SmartSpend, I want to be able to manage my spending categories and customize them.

**Acceptance criteria**:

- User should be able to create new category and select Icon, Color, Name and Type for it.
- User should be able to manage categories (edit, merge and delete them).

**Comment by jhoneysoup** [comment]
Tested:


![Image](https://user-images.githubusercontent.com/122827384/230898750-b902c3d9-c690-4d2f-b03c-af10829418cc.png)



![Image](https://user-images.githubusercontent.com/122827384/230899006-dde740d5-9006-49f3-bcb0-1b0683411410.png)



![Image](https://user-images.githubusercontent.com/122827384/230899034-502129e4-70dc-4888-926f-0f6ca1185a1c.png)



![Image](https://user-images.githubusercontent.com/122827384/230899054-b1b84e3a-4307-49c1-8f79-ea62d0694732.png)
