### ISSUE TITLE
Fix Swagger doc

### ISSUE THREAD

**Issue by nikita-remeslov** [BinaryStudioAcademy/bsa-winter-2022-2023-smartspend#93]

**Comment by jhoneysoup** [comment]
tested: 


![Image](https://user-images.githubusercontent.com/122827384/227900340-836147a5-2760-44cf-bfd9-c217b5117162.png)



![Image](https://user-images.githubusercontent.com/122827384/227900405-3ca1e41f-1562-4daa-84da-61e17828fcfc.png)



![Image](https://user-images.githubusercontent.com/122827384/227900462-f437d15f-1ca3-4264-b792-8b8aa557174e.png)



![Image](https://user-images.githubusercontent.com/122827384/227900555-7df95f69-12e4-43f6-b971-43f00ef1bb4f.png)




![Image](https://user-images.githubusercontent.com/122827384/227900725-fc371bd8-be3b-4159-909e-10753832d9fa.png)
